### ISSUE TITLE
Could not find a version of package yireo/magento2-salesblock2-by-ip matching your minimum-stability (stable)

### ISSUE THREAD

**Issue by sergey-nechaev** [yireo/Yireo_SalesBlock2ByIp#1]
`composer require yireo/magento2-salesblock2-by-ip` gives this error:
```
[InvalidArgumentException]                                                                                                                                                        
Could not find a version of package yireo/magento2-salesblock2-by-ip matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.
```

I believe you should create a release like this - https://github.com/yireo/Yireo_SalesBlock2ByEmail/releases to make this package `stable` to respect the Magento stability level which is `stable`.

Reference:
https://github.com/magento/magento2/blob/2.4-develop/composer.json
https://getcomposer.org/doc/04-schema.md#minimum-stability

**Comment by jissereitsma** [comment]
You are spot on to mention there simply should be a release. I've just released it. Sorry for not having done this earlier.
